import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: [
      'test/conformance/pdf-writer.conformance.test.ts',
      'test/conformance/reviewed-pdf.test.ts',
      'apps/service/test/session-security.test.ts',
      'apps/service/test/recovery.test.ts',
      'apps/service/test/pdf-save-coordinator.test.ts',
      'apps/service/test/export-transaction.test.ts',
      'apps/service/test/replace-original.test.ts',
      'apps/service/test/synctex.test.ts',
      'apps/service/test/task-binding-registry.test.ts',
      'apps/service/test/launch-host.test.ts',
      'apps/service/test/open-command.test.ts',
      'apps/service/test/doctor-command.test.ts',
      'apps/service/test/hook-contract.test.ts',
      'apps/service/test/context-command.test.ts',
      'apps/service/test/live-context-service.test.ts',
      'apps/service/test/pdf-evidence-service.test.ts',
      'apps/service/test/source-reconciliation-service.test.ts',
      'apps/service/test/live-source-workflow.test.ts',
      'apps/service/test/codex-live-context.integration.test.ts',
      'packages/core/test/live-context.test.ts',
      'packages/core/test/review-commands.test.ts',
      'apps/web/test/save-state-controller.test.ts',
      'apps/web/test/proofread-gestures.test.tsx',
      'apps/web/test/selection-anchor.test.ts',
      'apps/web/test/selection-state.test.ts',
      'apps/web/test/review-surface-state.test.ts',
      'apps/web/test/viewer-controls.test.ts',
      'apps/web/test/viewer-framing.test.ts',
      'apps/web/test/review-layout.test.tsx',
      'apps/web/test/annotation-projection.test.ts',
      'apps/web/test/production-review-app.test.tsx',
      'apps/web/test/codex-context-status.test.tsx',
      'apps/web/test/existing-annotations.test.ts',
      'apps/vscode/test/extension.test.ts',
      'packaging/macos/packaging.test.ts',
    ],
  },
});
